apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    uid: syscloud-influxdb
    url: ${INFLUXDB_URL}
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
